### ISSUE TITLE
problem when runing  estimate_convergent_regimes with pBIC option

### ISSUE THREAD

**Issue by Gonzobilbao** [khabbazian/l1ou#40] opened 2018-11-26 21:13 UTC
Hi,
I am running the following piece of code

>lasso1TreeB1_pBIC<-estimate_shift_configuration(AdjTree, Y[,1], criterion="pBIC")
>lasso1TreeB1_pBIC$nShifts

[1] 4

>lasso2TreeB1_pBIC <- estimate_convergent_regimes(lasso1TreeB1_pBIC, criterion="pBIC")

Error: $ operator is invalid for atomic vectors

However, when I use AICc or BIC instead of pBIC, it seems to work and $nShifts gives:

[1] 4

I have checked the manual for the function but not sure what is not working. Is there any problem with pBIC when using estimate_convergent_regimes? Something I am overlooking? Thank you!

**Comment by khabbazian** [comment] 2020-05-20 20:30
close it because of not having enough info to fix to reproduce ...

**Closed as completed by khabbazian** 2020-05-20 20:30 UTC
